---
title: "Webhook Files"
author: "Joe Shaw"
date: today
date-format: "DD/MM/YYYY"
format: pdf
editor: visual
---

```{r}
#| label: packages
#| include: FALSE

library(tidyverse)
library(here)

```

```{r}
#| label: read-data
#| echo: FALSE

webhook_day <- "18-01-24"

all_files <- list.files(path = here::here(str_c("data/", webhook_day)),
                        pattern = "*.txt",
                        full.names = TRUE)

process_file <- function(file_path) {
  
  webhook_regex <- regex(
    r"[
    GET:\shttp://localhost:1200/     # Doesn't change
    (.+)                             # Bit we want
    \?                               # Question mark is end of section
    model=
    (.+)                             # Model text                            
    &id=
    (\d{6})                          # Referral ID
    \n
    ]", 
    comments = TRUE)
  
  file_regex <- regex(
    r"[
    .+
    (\d{4}-\d{2}-\d{2}-\d{2}-\d{2}) # timestamp
    .+
    .txt
    ]",
    comments = TRUE)
  
  file_string <- read_file(file_path)

  output <- data.frame(
    filename = file_path,
    date = as_datetime(str_extract(string = file_path, pattern = file_regex, group = 1),
                format = "%Y-%m-%d-%H-%M"),
    section = str_extract(string = file_string, pattern = webhook_regex, group = 1),
    model = str_extract(string = file_string, pattern = webhook_regex, group = 2),
    referral_id = str_extract(string = file_string, pattern = webhook_regex, group = 3))
  
  return(output)

}

webhook_df <- all_files |> 
  map(\(all_files) process_file(
    file_path = all_files
  )) |>
  list_rbind()

```
## Sample IDs

This analysis looks at **`r length(all_files)`** webhook files.

```{r}
#| label: files-per-sample
#| echo: FALSE

file_sample_summary <- webhook_df |> 
  group_by(referral_id) |> 
  summarise(files_per_sample = n(), .groups = "drop_last") 

ggplot(file_sample_summary, aes(x = files_per_sample, y = )) +
  geom_histogram(binwidth = 1) +
  theme_bw() +
  labs(x = "Number of files per sample",
       y = "Number of samples",
       title = "Files generated per sample",
       subtitle = str_c("Data from ", webhook_day))

```

{{< pagebreak >}}

There is a similar pattern to the previous data for 05/01/2024, but 1 sample has 30 files associated with it (see below).

```{r}
#| label: big-hitter
#| echo: FALSE

big_hitter <- webhook_df |> 
  filter(referral_id == 458683) |>
  arrange(date) |>  
  select(-c(model, filename)) |>  
  relocate(referral_id)

knitr::kable(big_hitter)

```

{{< pagebreak >}}

Here is the breakdown by the "model" section of the string, for the same data.

```{r}
#| label: models
#| echo: FALSE

webhook_df |> 
  group_by(model) |> 
  summarise(total = n(), .groups = "drop_last") |> 
  ggplot(aes(x = model, y = total)) +
  geom_col(aes(fill = model)) +
  theme_bw()

```

```{r}
#| label: model-section-combo
#| include: FALSE

webhook_df |> 
  group_by(section, model) |> 
  summarise(total = n(), .groups = "drop_last") |> 
  mutate(combo = str_c(section, "_", model)) |> 
  ggplot(aes(x = combo, y = total)) +
  geom_col(aes(fill = combo)) +
  theme_bw() +
  theme(axis.text.x = element_blank())

```




